### ISSUE TITLE
Error Syncing Repo For SM-T530 matissewifi

### ISSUE THREAD

**Issue by BAProductions** [matissewifi/manifest#1]
Hi this is my first time making and android custom rom althose I'm a programer/Linux Pro I'm stuck and no matter what i do or try i keep getting a few error when i sync the repo using your file on github below are the error im getting.
I'm getting this error when I run repo sync
**Fatal: couldn't find remote ref refs/heads/lineage-15.1** & This
**Error: cannot fetch matissewifi/device_matissewifi** + 
I'm also getting this error when I run repo sync -l
**revision refs/heads/lineage-15.1 in matissewifi/device_matissewifi not found**. 
Can it be fixed & if so how do i fix it & is it a time consuming fix or something simple and easy to fix im lost

**Comment by matteo0026** [comment]
Look pull requests. I just found the error.

**Comment by BAProductions** [comment]
Never mind i fixed my using the getlab repo by https://gitlab.com/ljani-matisse witch i forked https://gitlab.com/users/mweb71/activity and im currently trying to patch the camera and microphone help would be greatly appreciated I'm also addind thing like hackerkeyboard gboard 

_Sent from my Galaxy Tab E 9.6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by matteo0026** [comment]
Don't add not requested stuff. If you are working on sources, just fix camera and microphone. After fixing all, you can make another branch and add what you want. Just because only someone would what you are adding.
